### PR TITLE
Draft Update node-hid to 2.1.2 to fix win32 error

### PR DESCRIPTION
**Pull request by Gatorzgaming**
Updates various packages by using `npm i node-hid` to fix 
```js 
rror: \\?\C:\Users\Admin\Documents\beamng-shifting-leds\node_modules\node-hid\build\Release\HID.node is not a valid Win32 application.
\\?\C:\Users\Admin\Documents\beamng-shifting-leds\node_modules\node-hid\build\Release\HID.node
    at Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at bindings (C:\Users\Admin\Documents\beamng-shifting-leds\node_modules\bindings\bindings.js:112:48)
    at loadBinding (C:\Users\Admin\Documents\beamng-shifting-leds\node_modules\node-hid\nodehid.js:25:42)
    at new HID (C:\Users\Admin\Documents\beamng-shifting-leds\node_modules\node-hid\nodehid.js:35:5)
    at Object.<anonymous> (C:\Users\Admin\Documents\beamng-shifting-leds\beamng-shifting-leds.js:31:11)
    at Module._compile (node:internal/modules/cjs/loader:1254:14) {
  code: 'ERR_DLOPEN_FAILED'
}```

### CODE REVIEW

**Comment by Gatorzgaming** [comment]
After testing this ingame it connects to beamNG but doesn't do the lights

**Review by Gatorzgaming — COMMENTED** [review]
After testing this causes breaking changes, looking into possible fixes

**Comment by Gatorzgaming** [comment]
@gamingdoom Does the patched version work for you? I am thinking this might be a windows thing...

**Comment by gamingdoom** [comment]
This PR works for me on Linux, are you sure that outgauge support is enabled in BeamNG and the port is set to 5555?

**Comment by Gatorzgaming** [comment]
> This PR works for me on Linux, are you sure that outgauge support is enabled in BeamNG and the port is set to 5555?

I am running it on Windows 11 23H2. That is probably why... It seems like it partially works on windows, but the way to interact with the wheel is different, I will make an issue / PR for this eventually

**Pull request merged**
